_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/models_generator/train_models.py
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 8
epochs:
    value: 1
model:
    value: convnext_large_1_epochs_1.0_lr
